const KEY='waypoint_v22_data';
const defaultTrip={
  trip:{name:'England Adventure 2026',start:'2026-07-06',end:'2026-08-07',privacy:'Local device only'},
  days:[
    {date:'2026-07-06',place:'London',title:'Arrive in London',activities:[{time:'Afternoon',title:'Arrive, settle in near Victoria Station',type:'travel'}]},
    {date:'2026-07-07',place:'London',title:'London exploring',activities:[{time:'Morning',title:'Classic London walk',type:'activity'}]},
    {date:'2026-07-08',place:'London',title:'London day',activities:[]},
    {date:'2026-07-09',place:'London',title:'Warner Bros. Studio Tour',activities:[{time:'Day',title:'Harry Potter Studio Tour from Watford Junction',type:'ticket'}]},
    {date:'2026-07-10',place:'London',title:'London final day',activities:[]},
    {date:'2026-07-11',place:'Cambridge',title:'Travel to Cambridge',activities:[{time:'Afternoon',title:'Punting or riverside walk',type:'activity'}]},
    {date:'2026-07-12',place:'Cambridge',title:'Cambridge',activities:[{time:'Day',title:'Colleges, bikes, bridges, and Sunday roast option',type:'activity'}]},
    {date:'2026-07-13',place:'York',title:"Elizabeth's Birthday in York",activities:[{time:'Afternoon',title:'Arrive in York and explore historic center',type:'travel'},{time:'Evening',title:'Birthday dinner',type:'restaurant'}]},
    {date:'2026-07-14',place:'York',title:'York',activities:[{time:'Day',title:'York Minster, Shambles, city walls',type:'activity'}]},
    {date:'2026-07-15',place:'York',title:'York extra night',activities:[]},
    {date:'2026-07-16',place:'Whitby',title:'Whitby',activities:[{time:'Day',title:'Whitby Abbey and seaside exploring',type:'activity'}]},
    {date:'2026-07-17',place:'Yorkshire Dales',title:'Yorkshire Dales begins',activities:[{time:'Day',title:'Drive into the Dales and settle in',type:'travel'}]},
    {date:'2026-07-18',place:'Yorkshire Dales',title:'Dales adventure',activities:[]},
    {date:'2026-07-19',place:'Yorkshire Dales',title:'Dales Sunday',activities:[{time:'Midday',title:'Sunday roast option',type:'restaurant'}]},
    {date:'2026-07-20',place:'Yorkshire Dales',title:'Dales hikes and villages',activities:[]},
    {date:'2026-07-21',place:'Yorkshire Dales',title:'Dales hikes and villages',activities:[]},
    {date:'2026-07-22',place:'Yorkshire Dales',title:'Dales hikes and villages',activities:[]},
    {date:'2026-07-23',place:'Yorkshire Dales',title:'Dales final full day',activities:[]},
    {date:'2026-07-24',place:'Yorkshire Dales',title:'Dales wrap-up',activities:[]},
    {date:'2026-07-25',place:'Cotswolds',title:'Travel to Cotswolds',activities:[]},
    {date:'2026-07-26',place:'Cotswolds',title:'Cotswolds Sunday',activities:[]},
    {date:'2026-07-27',place:'Cotswolds',title:'Cotswolds villages',activities:[]},
    {date:'2026-07-28',place:'Cotswolds',title:'Cotswolds walking day',activities:[]},
    {date:'2026-07-29',place:'Cotswolds',title:'Cotswolds',activities:[]},
    {date:'2026-07-30',place:'Cotswolds',title:'Cotswolds',activities:[]},
    {date:'2026-07-31',place:'Cotswolds',title:'Cotswolds final day',activities:[]},
    {date:'2026-08-01',place:'Castle Combe',title:'Travel to Castle Combe',activities:[]},
    {date:'2026-08-02',place:'Castle Combe',title:'Castle Combe',activities:[]},
    {date:'2026-08-03',place:'Castle Combe',title:'Castle Combe',activities:[]},
    {date:'2026-08-04',place:'Castle Combe',title:'Castle Combe final full day',activities:[]},
    {date:'2026-08-05',place:'Castle Combe',title:'Castle Combe wrap-up',activities:[]},
    {date:'2026-08-06',place:'Winchester',title:'Winchester',activities:[{time:'Day',title:'Great Hall and St Catherine’s Hill',type:'activity'}]},
    {date:'2026-08-07',place:'London / Heathrow',title:'Fly home',activities:[{time:'Day',title:'Return home',type:'flight'}]}
  ],
  reservations:[], journals:[], places:[], favorites:[]
};
let state={view:'home', selectedDate:null, modal:null, editing:null, search:''};
let data=load();
function load(){try{return {...structuredClone(defaultTrip),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(e){return structuredClone(defaultTrip)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function fmtDate(d){return new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}
function longDate(d){return new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'})}
function todayDate(){const now=new Date(); const s=data.trip.start,e=data.trip.end; const iso=now.toISOString().slice(0,10); return iso<s?s:iso>e?e:iso}
function dayFor(date){return data.days.find(x=>x.date===date)}
function reservationsFor(date){return data.reservations.filter(r=>r.date===date).sort((a,b)=>(a.time||'').localeCompare(b.time||''))}
function journalsFor(date){return data.journals.filter(j=>j.date===date)}
function setView(v,opts={}){state={...state,view:v,...opts,modal:null,editing:null};render(); window.scrollTo(0,0)}
function appShell(inner){return `<div class="app">${inner}${nav()}</div>`}
function nav(){const items=[['home','🏠','Home'],['days','📅','Days'],['reservations','🎟️','Reserve'],['journal','📷','Journal'],['settings','⚙️','Settings']];return `<div class="bottom">${items.map(i=>`<button class="navbtn ${state.view===i[0]?'active':''}" onclick="setView('${i[0]}')"><span class="ico">${i[1]}</span>${i[2]}</button>`).join('')}</div>`}
function hero(title,sub){return `<div class="hero"><div class="eyebrow">Waypoint</div><h1>${title}</h1><p>${sub}</p></div>`}
function render(){let html=''; if(state.view==='home')html=home(); if(state.view==='days')html=days(); if(state.view==='day')html=dayView(state.selectedDate); if(state.view==='reservations')html=reservations(); if(state.view==='journal')html=journal(); if(state.view==='settings')html=settings(); document.getElementById('app').innerHTML=appShell(html)+modal(); if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{});}
function home(){const td=todayDate(),d=dayFor(td);const count=data.days.length;const res=reservationsFor(td);return `${hero('Waypoint',data.trip.name)}<main class="content"><div class="card"><div class="row"><div><span class="pill">🇬🇧 England Adventure</span><h2 class="section-title">Today: ${d.place}</h2><div class="muted">${longDate(td)} · Day ${data.days.indexOf(d)+1} of ${count}</div></div><button class="btn" onclick="setView('day',{selectedDate:'${td}'})">Open</button></div></div><div class="grid"><button class="tile" onclick="setView('days')">📅<b>Daily Timeline</b><span>Activities, reservations, and journal by date.</span></button><button class="tile" onclick="openAdd('reservation','${td}')">🍽️<b>Add Reservation</b><span>Date picker and time picker included.</span></button><button class="tile" onclick="openAdd('journal','${td}')">📷<b>Add Journal</b><span>Notes, favorite memory, and photos.</span></button><button class="tile" onclick="setView('settings')">💾<b>Backup / Share</b><span>Export for Julie or restore a backup.</span></button></div><h2 class="section-title">Today's Reservations</h2><div class="list">${res.length?res.map(resCard).join(''):'<div class="empty">No reservations for today yet.</div>'}</div></main>`}
function days(){return `${top('Daily Timeline')}<main class="content"><div class="search"><input placeholder="Search days, places, activities..." value="${state.search}" oninput="state.search=this.value;render()"></div><br><div class="list">${data.days.filter(d=>JSON.stringify(d).toLowerCase().includes(state.search.toLowerCase())).map(d=>`<button class="item" onclick="setView('day',{selectedDate:'${d.date}'})"><div class="row"><div><div class="item-title">${fmtDate(d.date)} · ${d.place}</div><div class="muted">${d.title}</div></div><span>›</span></div></button>`).join('')}</div></main>`}
function dayView(date){const d=dayFor(date);const res=reservationsFor(date);const journals=journalsFor(date);let events=[...(d.activities||[]).map(a=>({...a,kind:'activity'})),...res.map(r=>({time:r.time,title:r.name,type:r.type||'reservation',kind:'reservation',id:r.id,meta:r.confirmation?`Confirmation: ${r.confirmation}`:''}))].sort((a,b)=>(a.time||'').localeCompare(b.time||''));return `${top('Day Details')}<main class="content"><div class="card day-head"><div><span class="pill">${d.place}</span><h2 class="section-title">${d.title}</h2><div class="muted">${longDate(date)}</div></div><div class="date-badge"><div class="mo">${new Date(date+'T12:00').toLocaleDateString(undefined,{month:'short'})}</div><div class="da">${new Date(date+'T12:00').getDate()}</div></div></div><h2 class="section-title">Timeline</h2><div class="timeline">${events.length?events.map(e=>`<div class="event"><div class="event-time">${e.time||'Anytime'} · ${icon(e.type)} ${label(e.type)}</div><div class="item-title">${e.title}</div>${e.location?`<div class="muted">${e.location}</div>`:''}${e.meta?`<div class="muted">${e.meta}</div>`:''}</div>`).join(''):'<div class="empty">No timeline items yet.</div>'}</div><h2 class="section-title">Journal</h2><div class="list">${journals.length?journals.map(journalCard).join(''):'<div class="empty">No journal entries yet.</div>'}</div></main><button class="fab" onclick="openQuick('${date}')">+</button>`}
function reservations(){return `${top('Reservations')}<main class="content"><button class="btn" onclick="openAdd('reservation')">+ Add Reservation</button><br><br><div class="list">${data.reservations.length?data.reservations.sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(resCard).join(''):'<div class="empty">No reservations yet.</div>'}</div></main>`}
function journal(){return `${top('Travel Journal')}<main class="content"><button class="btn" onclick="openAdd('journal')">+ Add Journal Entry</button><br><br><div class="list">${data.journals.length?data.journals.sort((a,b)=>b.date.localeCompare(a.date)).map(journalCard).join(''):'<div class="empty">No journal entries yet.</div>'}</div></main>`}
function settings(){return `${top('Settings & Sharing')}<main class="content"><div class="card"><h2>Storage</h2><p class="muted">Your Waypoint data is stored on this device only unless you export and share a backup.</p><span class="pill">🔒 Local device only</span></div><div class="card"><h2>Share with Julie</h2><p class="muted">Export a backup, AirDrop or send it to Julie, then import it on her phone.</p><div class="actions"><button class="btn" onclick="exportData()">Export Backup</button><label class="btn secondary">Import<input type="file" accept="application/json" onchange="importData(event)" hidden></label></div></div><div class="card"><h2>Reset</h2><p class="muted">This only affects the device you are using now.</p><button class="btn secondary danger" onclick="resetData()">Reset Local Data</button></div></main>`}
function top(t){return `<div class="topbar"><button class="back" onclick="setView('home')">← Home</button></div><main class="content"><h1>${t}</h1></main>`}
function icon(t){return ({restaurant:'🍽️',hotel:'🏨',train:'🚆',flight:'✈️',ticket:'🎟️',parking:'🚗',fishing:'🎣',hike:'🥾',show:'🎭',activity:'📍',reservation:'🎟️',other:'📌'})[t]||'📌'}
function label(t){return ({restaurant:'Restaurant',hotel:'Hotel',train:'Train',flight:'Flight',ticket:'Attraction',parking:'Parking',fishing:'Fishing',hike:'Hike',show:'Show',activity:'Activity',other:'Other'})[t]||'Reservation'}
function resCard(r){return `<div class="item"><div class="row"><div><div class="item-title">${icon(r.type)} ${r.name}</div><div class="muted">${fmtDate(r.date)} ${r.time?`· ${r.time}`:''}${r.location?` · ${r.location}`:''}</div>${r.confirmation?`<div class="muted">Confirmation: ${r.confirmation}</div>`:''}</div><button class="btn ghost" onclick="editReservation('${r.id}')">Edit</button></div></div>`}
function journalCard(j){return `<div class="item"><div class="row"><div><div class="item-title">${fmtDate(j.date)} · ${j.title||'Journal Entry'}</div><div class="muted">${j.note?j.note.slice(0,95):''}</div></div><button class="btn ghost" onclick="editJournal('${j.id}')">Edit</button></div>${j.photos?.length?`<div class="photo-grid">${j.photos.slice(0,6).map(p=>`<img src="${p}">`).join('')}</div>`:''}</div>`}
function openQuick(date){state.modal={type:'quick',date};render()}
function openAdd(type,date=''){state.modal={type,date:date||todayDate()};state.editing=null;render()}
function editReservation(id){state.editing=data.reservations.find(r=>r.id===id);state.modal={type:'reservation',date:state.editing.date};render()}
function editJournal(id){state.editing=data.journals.find(j=>j.id===id);state.modal={type:'journal',date:state.editing.date};render()}
function closeModal(){state.modal=null;state.editing=null;render()}
function modal(){if(!state.modal)return''; if(state.modal.type==='quick')return `<div class="modal show"><div class="sheet"><h2>Add to ${fmtDate(state.modal.date)}</h2><div class="grid"><button class="tile" onclick="openAdd('reservation','${state.modal.date}')">🍽️<b>Reservation</b><span>Restaurant, hotel, tickets, parking.</span></button><button class="tile" onclick="openAdd('journal','${state.modal.date}')">📷<b>Journal</b><span>Entry with photos.</span></button></div><br><button class="btn secondary" onclick="closeModal()">Cancel</button></div></div>`; if(state.modal.type==='reservation')return reservationForm(); if(state.modal.type==='journal')return journalForm();}
function reservationForm(){const r=state.editing||{date:state.modal.date,type:'restaurant'};return `<div class="modal show"><div class="sheet"><h2>${state.editing?'Edit':'Add'} Reservation</h2><div class="field"><label>Type</label><select id="resType"><option value="restaurant">🍽️ Restaurant</option><option value="hotel">🏨 Hotel</option><option value="train">🚆 Train</option><option value="flight">✈️ Flight</option><option value="ticket">🎟️ Attraction / Ticket</option><option value="parking">🚗 Parking</option><option value="fishing">🎣 Fishing</option><option value="hike">🥾 Hike</option><option value="show">🎭 Show</option><option value="other">📌 Other</option></select></div><div class="field"><label>Date</label><input id="resDate" type="date" value="${r.date||state.modal.date}" min="${data.trip.start}" max="${data.trip.end}"></div><div class="field"><label>Time</label><input id="resTime" type="time" value="${r.time||''}"></div><div class="field"><label>Name</label><input id="resName" placeholder="Restaurant, attraction, hotel..." value="${esc(r.name||'')}"></div><div class="field"><label>Location / Address</label><input id="resLoc" placeholder="Address or town" value="${esc(r.location||'')}"></div><div class="field"><label>Confirmation Number</label><input id="resConf" value="${esc(r.confirmation||'')}"></div><div class="field"><label>Link</label><input id="resLink" placeholder="Website or confirmation link" value="${esc(r.link||'')}"></div><div class="field"><label>Notes</label><textarea id="resNotes">${esc(r.notes||'')}</textarea></div><div class="actions"><button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn" onclick="saveReservation()">Save</button></div>${state.editing?'<br><button class="btn secondary danger" onclick="deleteReservation()">Delete</button>':''}</div></div>`}
function journalForm(){const j=state.editing||{date:state.modal.date,photos:[]};return `<div class="modal show"><div class="sheet"><h2>${state.editing?'Edit':'Add'} Journal</h2><div class="field"><label>Date</label><input id="jDate" type="date" value="${j.date||state.modal.date}" min="${data.trip.start}" max="${data.trip.end}"></div><div class="field"><label>Title</label><input id="jTitle" placeholder="A favorite moment..." value="${esc(j.title||'')}"></div><div class="field"><label>Journal Entry</label><textarea id="jNote" placeholder="What happened today?">${esc(j.note||'')}</textarea></div><div class="field"><label>Favorite Memory</label><input id="jFav" value="${esc(j.favorite||'')}"></div><div class="field"><label>Funniest Moment</label><input id="jFunny" value="${esc(j.funny||'')}"></div><div class="field"><label>Best Meal</label><input id="jMeal" value="${esc(j.meal||'')}"></div><div class="field"><label>Photos</label><input id="jPhotos" type="file" accept="image/*" multiple></div>${j.photos?.length?`<div class="photo-grid">${j.photos.map(p=>`<img src="${p}">`).join('')}</div>`:''}<div class="actions"><button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn" onclick="saveJournal()">Save</button></div>${state.editing?'<br><button class="btn secondary danger" onclick="deleteJournal()">Delete</button>':''}</div></div>`}
function saveReservation(){const obj={id:state.editing?.id||uid(),type:val('resType'),date:val('resDate'),time:val('resTime'),name:val('resName')||'Untitled Reservation',location:val('resLoc'),confirmation:val('resConf'),link:val('resLink'),notes:val('resNotes')}; if(state.editing){data.reservations=data.reservations.map(r=>r.id===obj.id?obj:r)}else data.reservations.push(obj); save(); state.modal=null; state.editing=null; setView('day',{selectedDate:obj.date});}
async function saveJournal(){const existing=state.editing||{};const files=[...document.getElementById('jPhotos').files];const photos=[...(existing.photos||[])];for(const f of files){photos.push(await fileToData(f))}const obj={id:existing.id||uid(),date:val('jDate'),title:val('jTitle'),note:val('jNote'),favorite:val('jFav'),funny:val('jFunny'),meal:val('jMeal'),photos}; if(state.editing){data.journals=data.journals.map(j=>j.id===obj.id?obj:j)}else data.journals.push(obj); save(); state.modal=null; state.editing=null; setView('day',{selectedDate:obj.date});}
function deleteReservation(){if(confirm('Delete this reservation?')){data.reservations=data.reservations.filter(r=>r.id!==state.editing.id);save();closeModal()}}
function deleteJournal(){if(confirm('Delete this journal entry?')){data.journals=data.journals.filter(j=>j.id!==state.editing.id);save();closeModal()}}
function val(id){return document.getElementById(id)?.value||''}
function esc(s){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function fileToData(file){return new Promise(res=>{const r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(file)})}
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Waypoint_England_Backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{data=JSON.parse(r.result);save();alert('Backup imported.')}catch(err){alert('Could not import this file.')}};r.readAsText(f)}
function resetData(){if(confirm('Reset Waypoint data on this device?')){localStorage.removeItem(KEY);data=structuredClone(defaultTrip);render()}}
render();
