let state={route:'home',data:null,selectedDay:null,query:''};
const $=s=>document.querySelector(s);const main=$('#main');
function fmtDate(d){const x=new Date(d+'T12:00:00');return x.toLocaleDateString(undefined,{month:'short',day:'numeric'});} 
function todayISO(){return new Date().toISOString().slice(0,10);} 
function trip(){return state.data.trips[0];}
function setHeader(title,sub){$('#pageTitle').textContent=title;$('#pageSubtitle').textContent=sub;}
function route(r){state.route=r;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.route===r));render();}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>route(b.dataset.route));
$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('wp-theme',document.body.classList.contains('dark')?'dark':'light');};
if(localStorage.getItem('wp-theme')==='dark')document.body.classList.add('dark');
$('#closeModal').onclick=closeModal;
function openModal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden');}
function closeModal(){$('#modal').classList.add('hidden');}
function download(name,obj){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function escapeHtml(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function daysUntil(){const start=new Date(trip().start+'T12:00:00');const now=new Date();return Math.ceil((start-now)/(1000*60*60*24));}
function currentDay(){const t=todayISO();const ds=trip().days;return ds.find(d=>d.date===t)||ds[0];}
function render(){if(state.route==='home')return renderHome();if(state.route==='england')return renderEngland();if(state.route==='journal')return renderJournal();if(state.route==='settings')return renderSettings();}
function renderHome(){setHeader('Waypoint','Your local-first personal app.');const t=trip();const left=daysUntil();main.innerHTML=`<div class="grid"><div class="card tool-card" onclick="route('england')"><div class="big-emoji">🇬🇧</div><h2>${t.name}</h2><p class="muted">${left>0?left+' days until departure':'Trip is underway or complete'}</p><div class="progress"><div style="width:18%"></div></div></div><div class="card tool-card" onclick="route('journal')"><div class="big-emoji">📷</div><h2>Photo Journal</h2><p class="muted">Daily memories, photos, best meal, favorite moments, and notes.</p></div><div class="card"><div class="big-emoji">🏡</div><h2>Real Estate</h2><p class="muted">Coming next: seller net sheet, mortgage tools, and listing checklists.</p></div><div class="card"><div class="big-emoji">🎣</div><h2>Fishing, Hiking & Family</h2><p class="muted">Future modules will plug into this same Waypoint engine.</p></div></div>`;}
function renderEngland(){setHeader('England Adventure','Editable itinerary, destinations, reservations, saved places.');const t=trip();state.selectedDay=state.selectedDay||currentDay().date;const day=t.days.find(d=>d.date===state.selectedDay)||t.days[0];main.innerHTML=`<div class="stack"><div class="card"><div class="row"><div><span class="pill">${t.start} → ${t.end}</span><h2>${t.name}</h2><p class="muted">${t.travelers.join(', ')}</p></div><button class="btn" onclick="addDay()">+ Add Day</button></div></div><div class="day-list">${t.days.map(d=>`<button class="day-chip ${d.date===day.date?'active':''}" onclick="selectDay('${d.date}')"><strong>${fmtDate(d.date)}</strong><br><span class="muted small">${escapeHtml(d.location)}</span><br>${escapeHtml(d.title)}</button>`).join('')}</div><div class="card"><div class="row"><div><h2>${fmtDate(day.date)} — ${escapeHtml(day.title)}</h2><p class="muted">${escapeHtml(day.location)}</p></div><button class="btn secondary" onclick="editDay('${day.date}')">Edit Day</button></div><div class="stack">${day.activities.map((a,i)=>`<div class="activity"><div class="row"><strong>${escapeHtml(a.time||'Anytime')} — ${escapeHtml(a.title)}</strong><button class="btn secondary small" onclick="editActivity('${day.date}',${i})">Edit</button></div><p class="muted">${escapeHtml(a.notes||'')}</p></div>`).join('')||'<p class="muted">No activities yet.</p>'}<button class="btn" onclick="addActivity('${day.date}')">+ Add Activity</button><button class="btn secondary" onclick="addJournalForDay('${day.date}')">📷 Add Journal Entry for This Day</button></div></div><div class="grid"><div class="card"><h2>Destinations</h2><div class="stack">${t.destinations.map(x=>`<div><strong>${escapeHtml(x.name)}</strong><br><span class="muted small">${escapeHtml(x.dates)} — ${escapeHtml(x.notes)}</span></div>`).join('')}</div></div><div class="card"><div class="row"><h2>Reservations</h2><button class="btn secondary" onclick="addReservation()">+ Add</button></div><div class="stack">${t.reservations.map((r,i)=>`<div><strong>${escapeHtml(r.name)}</strong><br><span class="muted small">${escapeHtml(r.date||'')} ${escapeHtml(r.time||'')} — ${escapeHtml(r.notes||'')}</span></div>`).join('')||'<p class="muted">No reservations added yet.</p>'}</div></div><div class="card"><div class="row"><h2>Saved Places</h2><button class="btn secondary" onclick="addPlace()">+ Add</button></div><div class="stack">${t.savedPlaces.map(p=>`<div><strong>${escapeHtml(p.name)}</strong><br><span class="muted small">${escapeHtml(p.type)} — ${escapeHtml(p.notes)}</span></div>`).join('')}</div></div></div></div>`;}
function selectDay(date){state.selectedDay=date;renderEngland();}
async function saveAndRender(){await saveData(state.data);render();}
function editDay(date){const d=trip().days.find(x=>x.date===date);openModal('Edit Day',`<div class="field"><label>Date</label><input id="dDate" value="${d.date}"></div><div class="field"><label>Title</label><input id="dTitle" value="${escapeHtml(d.title)}"></div><div class="field"><label>Location</label><input id="dLoc" value="${escapeHtml(d.location)}"></div><button class="btn" onclick="saveDay('${date}')">Save Day</button>`);} 
async function saveDay(old){const d=trip().days.find(x=>x.date===old);d.date=$('#dDate').value;d.title=$('#dTitle').value;d.location=$('#dLoc').value;state.selectedDay=d.date;closeModal();await saveAndRender();}
function addDay(){openModal('Add Day',`<div class="field"><label>Date</label><input id="dDate" placeholder="2026-07-06"></div><div class="field"><label>Title</label><input id="dTitle"></div><div class="field"><label>Location</label><input id="dLoc"></div><button class="btn" onclick="saveNewDay()">Add Day</button>`);} 
async function saveNewDay(){trip().days.push({date:$('#dDate').value,title:$('#dTitle').value,location:$('#dLoc').value,activities:[]});trip().days.sort((a,b)=>a.date.localeCompare(b.date));state.selectedDay=$('#dDate').value;closeModal();await saveAndRender();}
function addActivity(date){openModal('Add Activity',`<div class="field"><label>Time</label><input id="aTime" placeholder="10:00 AM"></div><div class="field"><label>Title</label><input id="aTitle"></div><div class="field"><label>Notes</label><textarea id="aNotes"></textarea></div><button class="btn" onclick="saveActivity('${date}')">Add Activity</button>`);} 
function editActivity(date,i){const a=trip().days.find(d=>d.date===date).activities[i];openModal('Edit Activity',`<div class="field"><label>Time</label><input id="aTime" value="${escapeHtml(a.time||'')}"></div><div class="field"><label>Title</label><input id="aTitle" value="${escapeHtml(a.title)}"></div><div class="field"><label>Notes</label><textarea id="aNotes">${escapeHtml(a.notes||'')}</textarea></div><button class="btn" onclick="saveActivity('${date}',${i})">Save Activity</button>`);} 
async function saveActivity(date,i=null){const d=trip().days.find(x=>x.date===date);const obj={time:$('#aTime').value,title:$('#aTitle').value,notes:$('#aNotes').value};if(i===null)d.activities.push(obj);else d.activities[i]=obj;closeModal();await saveAndRender();}
function addReservation(){openModal('Add Reservation',`<div class="field"><label>Name</label><input id="rName"></div><div class="field"><label>Date</label><input id="rDate"></div><div class="field"><label>Time</label><input id="rTime"></div><div class="field"><label>Notes / confirmation</label><textarea id="rNotes"></textarea></div><button class="btn" onclick="saveReservation()">Save Reservation</button>`);} 
async function saveReservation(){trip().reservations.push({name:$('#rName').value,date:$('#rDate').value,time:$('#rTime').value,notes:$('#rNotes').value});closeModal();await saveAndRender();}
function addPlace(){openModal('Add Saved Place',`<div class="field"><label>Name</label><input id="pName"></div><div class="field"><label>Type</label><input id="pType" placeholder="Restaurant, hike, parking, historic site"></div><div class="field"><label>Notes</label><textarea id="pNotes"></textarea></div><button class="btn" onclick="savePlace()">Save Place</button>`);} 
async function savePlace(){trip().savedPlaces.push({name:$('#pName').value,type:$('#pType').value,notes:$('#pNotes').value});closeModal();await saveAndRender();}
function renderJournal(){setHeader('Photo Journal','Entries and photos stay local on this device unless you export them.');const entries=state.data.journals.filter(j=>j.tripId==='england-2026').sort((a,b)=>b.date.localeCompare(a.date));main.innerHTML=`<div class="stack"><div class="card row"><div><h2>England Photo Journal</h2><p class="muted">Add daily memories, best meal, funny moments, and photos.</p></div><button class="btn" onclick="addJournalForDay('${state.selectedDay||currentDay().date}')">+ New Entry</button></div>${entries.map((j,i)=>`<div class="journal-entry"><div class="row"><div><strong>${fmtDate(j.date)} — ${escapeHtml(j.title||'Journal Entry')}</strong><br><span class="muted small">${escapeHtml(j.location||'')}</span></div><button class="btn secondary" onclick="editJournal('${j.id}')">Edit</button></div><p>${escapeHtml(j.notes||'')}</p>${j.favorite?`<p class="muted"><strong>Favorite:</strong> ${escapeHtml(j.favorite)}</p>`:''}${j.funny?`<p class="muted"><strong>Funniest moment:</strong> ${escapeHtml(j.funny)}</p>`:''}${j.bestMeal?`<p class="muted"><strong>Best meal:</strong> ${escapeHtml(j.bestMeal)}</p>`:''}<div class="photos">${(j.photos||[]).map(p=>`<img class="photo-thumb" src="${p}">`).join('')}</div></div>`).join('')||'<div class="card"><p class="muted">No journal entries yet.</p></div>'}</div>`;}
function addJournalForDay(date){openJournalModal({id:'j-'+Date.now(),tripId:'england-2026',date,title:'',location:(trip().days.find(d=>d.date===date)||{}).location||'',notes:'',favorite:'',funny:'',bestMeal:'',photos:[]},true);} 
function editJournal(id){const j=state.data.journals.find(x=>x.id===id);openJournalModal(j,false);} 
function openJournalModal(j,isNew){openModal(isNew?'New Journal Entry':'Edit Journal Entry',`<div class="field"><label>Date</label><input id="jDate" value="${j.date}"></div><div class="field"><label>Title</label><input id="jTitle" value="${escapeHtml(j.title||'')}"></div><div class="field"><label>Location</label><input id="jLoc" value="${escapeHtml(j.location||'')}"></div><div class="field"><label>Notes</label><textarea id="jNotes">${escapeHtml(j.notes||'')}</textarea></div><div class="field"><label>Favorite memory</label><input id="jFav" value="${escapeHtml(j.favorite||'')}"></div><div class="field"><label>Funniest moment</label><input id="jFunny" value="${escapeHtml(j.funny||'')}"></div><div class="field"><label>Best meal</label><input id="jMeal" value="${escapeHtml(j.bestMeal||'')}"></div><div class="field"><label>Add photos</label><input id="jPhotos" type="file" accept="image/*" multiple></div><p class="muted small">Photos are stored locally in this browser database. Use Export Backup to save a copy.</p><button class="btn" onclick="saveJournal('${j.id}',${isNew})">Save Journal</button>`);window.tempJournal=j;}
async function fileToDataURL(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file);});}
async function saveJournal(id,isNew){let j=isNew?window.tempJournal:state.data.journals.find(x=>x.id===id);j.date=$('#jDate').value;j.title=$('#jTitle').value;j.location=$('#jLoc').value;j.notes=$('#jNotes').value;j.favorite=$('#jFav').value;j.funny=$('#jFunny').value;j.bestMeal=$('#jMeal').value;j.photos=j.photos||[];const files=[...$('#jPhotos').files];for(const f of files){j.photos.push(await fileToDataURL(f));}if(isNew)state.data.journals.push(j);closeModal();state.route='journal';await saveAndRender();}
function renderSettings(){setHeader('Settings','Privacy, backup, restore, and app info.');main.innerHTML=`<div class="stack"><div class="card"><h2>Privacy</h2><p class="muted">Waypoint stores your itinerary, journal entries, reservations, saved places, and photos locally on this device using IndexedDB. Nothing is uploaded to GitHub, ChatGPT, or a cloud server unless you manually export and save/share the backup file.</p></div><div class="card stack"><h2>Backup</h2><button class="btn" onclick="exportBackup()">⬇ Export Waypoint Backup</button><button class="btn secondary" onclick="document.getElementById('importFile').click()">⬆ Import Backup</button><button class="btn danger" onclick="resetData()">Reset Local Data</button></div><div class="card"><h2>Version</h2><p class="muted">Waypoint 2.0 — modular app structure, local database, editable England trip, and photo journal.</p></div></div>`;}
function exportBackup(){download('Waypoint_Backup_'+todayISO()+'.json',state.data);} 
$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;const text=await f.text();state.data=JSON.parse(text);await saveData(state.data);alert('Backup imported.');render();};
async function resetData(){if(confirm('Reset all local Waypoint data on this device?')){state.data=structuredClone(window.WAYPOINT_DEFAULT_DATA);await saveData(state.data);render();}}
(async function(){state.data=await initData();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();})();
window.route=route;window.selectDay=selectDay;window.editDay=editDay;window.saveDay=saveDay;window.addDay=addDay;window.saveNewDay=saveNewDay;window.addActivity=addActivity;window.editActivity=editActivity;window.saveActivity=saveActivity;window.addReservation=addReservation;window.saveReservation=saveReservation;window.addPlace=addPlace;window.savePlace=savePlace;window.addJournalForDay=addJournalForDay;window.editJournal=editJournal;window.saveJournal=saveJournal;window.exportBackup=exportBackup;window.resetData=resetData;
